# Generated by Django 4.1.7 on 2023-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podik',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('available', models.BooleanField()),
                ('price', models.IntegerField()),
                ('currencyId', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('categoryId', models.IntegerField()),
                ('vendorCode', models.IntegerField()),
                ('quantity_in_stock', models.IntegerField()),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('piture', models.CharField(max_length=255)),
                ('param', models.CharField(max_length=255)),
            ],
        ),
    ]
