# Generated by Django 4.1.7 on 2023-03-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_piture_podik_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podik',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
